/**
 * Partnership ADS 的演示数据集。
 *
 * 移植自原型 `js/data.js`，数值逐字取自 Figma 稿。**一份数据喂所有页面** ——
 * Overview / Campaigns / Reports / campaign 详情读的是同一批对象，
 * 所以在一处改动会在其他页面同步反映，而不是每屏各造一份假数据。
 *
 * 原型解决过 Figma 稿里的两处自相矛盾，这里沿用同样的取舍：
 *   - **市场**：表格里八个 campaign 全标 `/ US`，而 Overview 显示 APAC/EU/NA/JP/SEA。
 *     取 Overview 的。
 *   - **创作者**：Overview 列了八个 KOL Network 里没有的名字。统一成十二人的一份名册。
 *
 * 还有一处**留着没动、值得决策**：`03.5 · Campaign detail` 把 Yahtzee 那条显示成
 * `$84,200 / $186,000`，而 Overview 显示 `$184,905`。这里全程用 Overview 的数。
 *
 * ⚠️ 接后端时这个文件整体被 DemoOverview 的映射替换，不要在它上面长业务逻辑。
 */

import type {
  AdAccount,
  Asset,
  Campaign,
  Creator,
  Delivery,
  HistoryEntry,
  LogEntry,
  Product,
  WorkspaceUser,
} from './types';

/** 演示用的固定时刻。刻意不用 Date.now()：截图要可复现，"14:05" 的时间戳才立得住。 */
export const NOW = '14:05';

export const USER: WorkspaceUser = {
  name: 'Han Xu',
  role: 'Workspace admin',
  initials: 'HX',
  email: 'han.xu@acme.com',
};

/** 触达人数，低于总曝光。同一个人看三条帖是三次曝光、一个人。 */
export const AUDIENCE = 48_200_000;
export const MONTHLY_SPEND_PCT = 68;

export const PRODUCTS: Product[] = [
  {
    id: 'yahtzee',
    name: 'Yahtzee',
    category: 'Mobile games · Casual',
    objective: 'App installs',
    icon: 'yahtzee',
    store: 'apps.apple.com/yahtzee',
    platforms: 'iOS + Android',
  },
  {
    id: 'loop',
    name: 'Loop Editor',
    category: 'Creator tools',
    objective: 'Subscriptions',
    icon: 'loop-editor',
    store: 'loopeditor.app',
    platforms: 'iOS + Web',
  },
  {
    id: 'nordwell',
    name: 'Nordwell',
    category: 'Apparel',
    objective: 'Purchases',
    icon: 'nordwell',
    store: 'nordwell.com',
    platforms: 'Web',
  },
  {
    id: 'paper',
    name: 'Papermark',
    category: 'Stationery',
    objective: 'Purchases',
    icon: 'papermark',
    store: 'papermark.store',
    platforms: 'Web',
  },
  {
    id: 'kotoba',
    name: 'Kotoba',
    category: 'Language learning',
    objective: 'App installs',
    icon: 'kotoba',
    store: 'apps.apple.com/kotoba',
    platforms: 'iOS + Android',
  },
  {
    id: 'lumea',
    name: 'Lumea Skin',
    category: 'Beauty · Skincare',
    objective: 'Purchases',
    icon: 'lumea-skin',
    store: 'lumeaskin.com',
    platforms: 'Web',
  },
  {
    id: 'vitalis',
    name: 'Vitalis',
    category: 'Health & fitness',
    objective: 'Sign-ups',
    icon: 'vitalis',
    store: 'vitalis.fit',
    platforms: 'iOS + Android',
  },
  {
    id: 'ampli',
    name: 'Ampli',
    category: 'Music · Audio',
    objective: 'App installs',
    icon: 'ampli',
    store: 'apps.apple.com/ampli',
    platforms: 'iOS + Android',
  },
];

export const CAMPAIGNS: Campaign[] = [
  {
    id: 'CMP-2408-031',
    name: 'Summer partnership',
    market: 'APAC',
    productId: 'yahtzee',
    status: 'running',
    owner: 'Han Xu',
    kols: 284,
    spend: 184_905,
    cap: 272_000,
    reach: 16_400_000,
    impressions: 16_400_000,
    installs: 84_819,
    cpi: 2.18,
    roas: 5.24,
    days: 12,
    channels: ['ig', 'tt', 'yt'],
    schedule: 'Sep 1 – Sep 30',
    delivering: 39,
    closed: 1,
  },
  {
    id: 'CMP-2408-027',
    name: 'Creator bundle',
    market: 'US',
    productId: 'loop',
    status: 'running',
    owner: 'Mina Kato',
    kols: 126,
    spend: 92_440,
    cap: 122_000,
    reach: 9_800_000,
    impressions: 9_800_000,
    installs: 39_504,
    cpi: 2.34,
    roas: 4.67,
    days: 8,
    channels: ['ig', 'tt'],
    schedule: 'Sep 4 – Sep 28',
    delivering: 22,
    closed: 0,
  },
  {
    id: 'CMP-2408-019',
    name: 'New season launch',
    market: 'EU',
    productId: 'nordwell',
    status: 'review',
    owner: 'Zoe Martin',
    kols: 68,
    spend: 48_160,
    cap: 107_000,
    reach: 6_100_000,
    impressions: 6_100_000,
    installs: 18_452,
    cpi: 2.61,
    roas: 3.92,
    days: 15,
    channels: ['yt', 'ig'],
    schedule: 'Sep 8 – Oct 4',
    delivering: 12,
    closed: 2,
  },
  {
    id: 'CMP-2408-014',
    name: 'Back-to-school creators',
    market: 'NA',
    productId: 'paper',
    status: 'running',
    owner: 'Leo Park',
    kols: 96,
    spend: 73_240,
    cap: 126_000,
    reach: 8_700_000,
    impressions: 8_700_000,
    installs: 32_264,
    cpi: 2.27,
    roas: 4.31,
    days: 19,
    channels: ['tt', 'ig'],
    schedule: 'Aug 20 – Sep 26',
    delivering: 18,
    closed: 0,
  },
  {
    id: 'CMP-2408-009',
    name: 'Holiday preview',
    market: 'JP',
    productId: 'kotoba',
    status: 'review',
    owner: 'Mina Kato',
    kols: 54,
    spend: 39_880,
    cap: 114_000,
    reach: 4_200_000,
    impressions: 4_200_000,
    installs: 14_662,
    cpi: 2.72,
    roas: 3.78,
    days: 21,
    channels: ['yt', 'tt'],
    schedule: 'Sep 12 – Oct 10',
    delivering: 9,
    closed: 1,
  },
  {
    id: 'CMP-2408-004',
    name: 'Always-on beauty',
    market: 'SEA',
    productId: 'lumea',
    status: 'running',
    owner: 'Han Xu',
    kols: 142,
    spend: 108_520,
    cap: 134_000,
    reach: 11_300_000,
    impressions: 11_300_000,
    installs: 52_936,
    cpi: 2.05,
    roas: 5.06,
    days: 26,
    channels: ['ig', 'yt', 'tt'],
    schedule: 'Aug 1 – Oct 15',
    delivering: 31,
    closed: 0,
  },
  {
    id: 'CMP-2407-088',
    name: 'Wellness spring',
    market: 'US',
    productId: 'vitalis',
    status: 'draft',
    owner: 'Noah King',
    kols: 48,
    spend: 28_720,
    cap: 62_000,
    reach: 3_400_000,
    impressions: 3_400_000,
    installs: 9972,
    cpi: 2.88,
    roas: 3.46,
    days: null,
    channels: ['ig', 'yt'],
    schedule: 'Oct 1 – Oct 31',
    delivering: 0,
    closed: 0,
  },
  {
    id: 'CMP-2407-071',
    name: 'Creator audio',
    market: 'US',
    productId: 'ampli',
    status: 'running',
    owner: 'Zoe Martin',
    kols: 72,
    spend: 44_960,
    cap: 76_000,
    reach: 5_800_000,
    impressions: 5_800_000,
    installs: 18_656,
    cpi: 2.41,
    roas: 4.12,
    days: null,
    channels: ['tt', 'yt'],
    schedule: 'Aug 15 – Sep 30',
    delivering: 16,
    closed: 0,
  },
];

export const CREATORS: Creator[] = [
  {
    id: 'ava',
    name: 'Ava Mitchell',
    handle: '@ava.mitchell',
    market: 'US',
    platforms: ['tt', 'ig'],
    tags: ['Beauty', 'Skincare'],
    followers: 1_200_000,
    eng: 4.8,
    cpe: 12,
    joined: 'Mar 2025',
    authorized: true,
    avgViews: 358_000,
    hue: 320,
  },
  {
    id: 'kenji',
    name: 'Kenji Sato',
    handle: '@kenjisato',
    market: 'JP',
    platforms: ['ig', 'yt'],
    tags: ['Tech', 'Gaming'],
    followers: 860_000,
    eng: 5.4,
    cpe: 14,
    joined: 'Jan 2025',
    authorized: true,
    avgViews: 244_000,
    hue: 205,
  },
  {
    id: 'lucia',
    name: 'Lucia Moreno',
    handle: '@luciamoreno',
    market: 'ES',
    platforms: ['tt'],
    tags: ['Fashion', 'Lifestyle'],
    followers: 2_100_000,
    eng: 6.1,
    cpe: 9,
    joined: 'Nov 2024',
    authorized: true,
    avgViews: 612_000,
    hue: 12,
  },
  {
    id: 'marcus',
    name: 'Marcus Bell',
    handle: '@marcusbell',
    market: 'US',
    platforms: ['yt'],
    tags: ['Fitness', 'Wellness'],
    followers: 540_000,
    eng: 3.9,
    cpe: 18,
    joined: 'Jun 2025',
    authorized: false,
    avgViews: 121_000,
    hue: 150,
  },
  {
    id: 'priya',
    name: 'Priya Nair',
    handle: '@priyanair',
    market: 'IN',
    platforms: ['ig', 'tt'],
    tags: ['Food', 'Travel'],
    followers: 1_600_000,
    eng: 5.2,
    cpe: 11,
    joined: 'Feb 2025',
    authorized: true,
    avgViews: 402_000,
    hue: 34,
  },
  {
    id: 'sofia',
    name: 'Sofia Lindqvist',
    handle: '@sofialind',
    market: 'SE',
    platforms: ['ig'],
    tags: ['Home', 'DIY'],
    followers: 420_000,
    eng: 4.1,
    cpe: 16,
    joined: 'Apr 2025',
    authorized: true,
    avgViews: 96_000,
    hue: 190,
  },
  {
    id: 'diego',
    name: 'Diego Torres',
    handle: '@diegotorres',
    market: 'MX',
    platforms: ['tt', 'yt'],
    tags: ['Music', 'Dance'],
    followers: 3_400_000,
    eng: 7.3,
    cpe: 8,
    joined: 'Sep 2024',
    authorized: true,
    avgViews: 890_000,
    hue: 275,
  },
  {
    id: 'amara',
    name: 'Amara Okafor',
    handle: '@amaraokafor',
    market: 'UK',
    platforms: ['ig', 'tt'],
    tags: ['Beauty', 'Fashion'],
    followers: 980_000,
    eng: 5.8,
    cpe: 10,
    joined: 'Dec 2024',
    authorized: true,
    avgViews: 288_000,
    hue: 300,
  },
  {
    id: 'yuki',
    name: 'Yuki Tanaka',
    handle: '@yukitanaka',
    market: 'JP',
    platforms: ['ig', 'yt'],
    tags: ['Anime', 'Art'],
    followers: 1_100_000,
    eng: 6.4,
    cpe: 13,
    joined: 'Mar 2025',
    authorized: true,
    avgViews: 331_000,
    hue: 240,
  },
  {
    id: 'chloe',
    name: 'Chloe Dubois',
    handle: '@chloedubois',
    market: 'FR',
    platforms: ['ig'],
    tags: ['Fashion', 'Beauty'],
    followers: 720_000,
    eng: 4.5,
    cpe: 15,
    joined: 'May 2025',
    authorized: false,
    avgViews: 158_000,
    hue: 350,
  },
  {
    id: 'samuel',
    name: 'Samuel Adeyemi',
    handle: '@samadeyemi',
    market: 'NG',
    platforms: ['tt', 'ig'],
    tags: ['Comedy', 'Music'],
    followers: 2_800_000,
    eng: 8.1,
    cpe: 7,
    joined: 'Oct 2024',
    authorized: true,
    avgViews: 744_000,
    hue: 96,
  },
  {
    id: 'elena',
    name: 'Elena Rossi',
    handle: '@elenarossi',
    market: 'IT',
    platforms: ['yt', 'tt'],
    tags: ['Food', 'Home'],
    followers: 640_000,
    eng: 4.9,
    cpe: 14,
    joined: 'Jul 2025',
    authorized: true,
    avgViews: 140_000,
    hue: 20,
  },
];

export const DELIVERY: Delivery[] = [
  {
    creatorId: 'ava',
    campaignId: 'CMP-2408-031',
    impressions: 250_000,
    clicks: 7600,
    revenue: 9317,
    pacing: 82,
    roas: 0.89,
    fit: 92,
    state: 'live',
    views: 142_000,
    cpi: 2.18,
  },
  {
    creatorId: 'kenji',
    campaignId: 'CMP-2408-031',
    impressions: 229_000,
    clicks: 5800,
    revenue: 9152,
    pacing: 88,
    roas: 1,
    fit: 88,
    state: 'live',
    views: 186_000,
    cpi: 2.41,
  },
  {
    creatorId: 'lucia',
    campaignId: 'CMP-2408-031',
    impressions: 194_000,
    clicks: 5800,
    revenue: 6292,
    pacing: 74,
    roas: 0.82,
    fit: 81,
    state: 'live',
    views: 398_000,
    cpi: 1.92,
  },
  {
    creatorId: 'marcus',
    campaignId: 'CMP-2408-031',
    impressions: 203_000,
    clicks: 7000,
    revenue: 6170,
    pacing: 72,
    roas: 0.82,
    fit: 63,
    state: 'rejected',
    views: 0,
    cpi: 0,
  },
  {
    creatorId: 'priya',
    campaignId: 'CMP-2408-031',
    impressions: 145_000,
    clicks: 4500,
    revenue: 5818,
    pacing: 63,
    roas: 0.89,
    fit: 74,
    state: 'live',
    views: 241_000,
    cpi: 2.76,
  },
  {
    creatorId: 'sofia',
    campaignId: 'CMP-2408-027',
    impressions: 117_000,
    clicks: 3400,
    revenue: 2615,
    pacing: 38,
    roas: 0.65,
    fit: 71,
    state: 'live',
    views: 118_000,
    cpi: 2.34,
  },
  {
    creatorId: 'diego',
    campaignId: 'CMP-2408-004',
    impressions: 312_000,
    clicks: 8900,
    revenue: 12_480,
    pacing: 91,
    roas: 1.18,
    fit: 95,
    state: 'live',
    views: 512_000,
    cpi: 2.05,
  },
  {
    creatorId: 'amara',
    campaignId: 'CMP-2408-004',
    impressions: 286_000,
    clicks: 6300,
    revenue: 10_240,
    pacing: 79,
    roas: 1.07,
    fit: 86,
    state: 'live',
    views: 274_000,
    cpi: 2.12,
  },
];

export const HISTORY: HistoryEntry[] = [
  {
    creatorId: 'ava',
    campaignId: 'CMP-2408-031',
    when: 'Sep 2026',
    live: true,
    installs: 12_480,
    roas: 4.2,
  },
  {
    creatorId: 'ava',
    campaignId: 'CMP-2408-027',
    when: 'Aug 2026',
    live: false,
    installs: 8120,
    roas: 3.6,
  },
  {
    creatorId: 'ava',
    campaignId: 'CMP-2408-014',
    when: 'Jul 2026',
    live: false,
    installs: 5640,
    roas: 2.9,
  },
  {
    creatorId: 'ava',
    campaignId: 'CMP-2408-004',
    when: 'May 2026',
    live: false,
    installs: 9310,
    roas: 3.8,
  },
];

export const ASSETS: Asset[] = [
  {
    id: 'a1',
    file: 'summer_hook_v3.mp4',
    kind: 'MP4',
    ratio: '9:16',
    len: '0:15',
    status: 'ready',
    origin: 'original',
    hue: 205,
    campaignId: 'CMP-2408-031',
  },
  {
    id: 'a2',
    file: 'summer_hook_v3_ava.mp4',
    kind: 'MP4',
    ratio: '9:16',
    len: '0:15',
    status: 'ready',
    origin: 'ai',
    creatorId: 'ava',
    hue: 205,
    campaignId: 'CMP-2408-031',
    perf: { impressions: 1_200_000, ctr: 3.4, roas: 4.2, campaigns: 3 },
  },
  {
    id: 'a3',
    file: 'unboxing_master.mp4',
    kind: 'MP4',
    ratio: '9:16',
    len: '0:22',
    status: 'ready',
    origin: 'original',
    hue: 24,
    campaignId: 'CMP-2408-027',
  },
  {
    id: 'a4',
    file: 'unboxing_master_kenji.mp4',
    kind: 'MP4',
    ratio: '9:16',
    len: '0:22',
    status: 'generating',
    origin: 'ai',
    creatorId: 'kenji',
    hue: 24,
    campaignId: 'CMP-2408-027',
  },
  {
    id: 'a5',
    file: 'hero_still_a.jpg',
    kind: 'JPG',
    ratio: '1:1',
    len: null,
    status: 'ready',
    origin: 'original',
    hue: 262,
    campaignId: 'CMP-2408-019',
  },
  {
    id: 'a6',
    file: 'hero_still_a_lucia.jpg',
    kind: 'JPG',
    ratio: '1:1',
    len: null,
    status: 'review',
    origin: 'ai',
    creatorId: 'lucia',
    hue: 262,
    campaignId: 'CMP-2408-019',
  },
  {
    id: 'a7',
    file: 'testimonial_cut.mp4',
    kind: 'MP4',
    ratio: '16:9',
    len: '0:30',
    status: 'ready',
    origin: 'original',
    hue: 38,
    campaignId: 'CMP-2408-014',
  },
  {
    id: 'a8',
    file: 'testimonial_cut_priya.mp4',
    kind: 'MP4',
    ratio: '16:9',
    len: '0:30',
    status: 'ready',
    origin: 'ai',
    creatorId: 'priya',
    hue: 38,
    campaignId: 'CMP-2408-014',
  },
  {
    id: 'a9',
    file: 'promo_card_q3.png',
    kind: 'PNG',
    ratio: '16:9',
    len: null,
    status: 'ready',
    origin: 'original',
    hue: 8,
    campaignId: 'CMP-2408-004',
  },
  {
    id: 'a10',
    file: 'promo_card_q3_diego.png',
    kind: 'PNG',
    ratio: '16:9',
    len: null,
    status: 'failed',
    origin: 'ai',
    creatorId: 'diego',
    hue: 8,
    campaignId: 'CMP-2408-004',
    error: 'The source file lost its audio track during transcode.',
  },
  {
    id: 'a11',
    file: 'launch_teaser.mp4',
    kind: 'MP4',
    ratio: '9:16',
    len: '0:08',
    status: 'ready',
    origin: 'original',
    hue: 150,
    campaignId: 'CMP-2408-009',
  },
  {
    id: 'a12',
    file: 'launch_teaser_amara.mp4',
    kind: 'MP4',
    ratio: '9:16',
    len: '0:08',
    status: 'ready',
    origin: 'ai',
    creatorId: 'amara',
    hue: 150,
    campaignId: 'CMP-2408-009',
  },
];

export const AUTOMATION_LOG: LogEntry[] = [
  { t: '16:40', title: 'ROAS crossed target', sub: '5.24× against 4.80× goal' },
  { t: '16:12', title: '1 ad rejected', sub: 'Marcus Bell · YouTube · ad closed' },
  { t: '15:30', title: '84,819 installs attributed', sub: 'MMP callbacks verified' },
  { t: '15:02', title: 'All 39 ads delivering', sub: 'spend pacing at 68%' },
  { t: '14:58', title: 'Published', sub: '40 ads pushed live' },
  { t: '14:52', title: 'Ready for publishing', sub: '40 ads prepared and waiting' },
  { t: '14:48', title: '40 ads built', sub: 'on act_8821345607' },
  { t: '14:02', title: 'Campaign created', sub: 'APAC · installs + purchase · $272,000' },
];

export const AD_ACCOUNTS: AdAccount[] = [
  {
    id: 'act_8821345607',
    platform: 'Meta Ads',
    owner: 'Acme Media',
    connected: '2 days ago',
    state: 'ok',
  },
  {
    id: 'act_5540912233',
    platform: 'TikTok Ads',
    owner: 'Acme Media',
    connected: '9 days ago',
    state: 'ok',
  },
  {
    id: 'act_2210458890',
    platform: 'Google Ads',
    owner: 'Acme Digital',
    connected: '41 days ago',
    state: 'stale',
  },
];
